title: Data formats and identifiers for charities working during COVID-19
description: test
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
# include:
#    - index.md
#    - formats/*.md
#    - identifiers/*.md
  exclude:
    - README.md

